apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-deployer-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: app-deployer
    app.kubernetes.io/component: app-of-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/alvesdmateus/app-deployer.git
    targetRevision: main
    path: deployments/argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
